[package]
name = "debts_challenge"
version = "0.1.0"
authors = ["brianrackle <N8$N#B!&mdwO>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
rand = "0.8.3"
